image: node

stages:
  - lint

eslint:
  stage: lint
  script:
    # Install eslint
    - |
      npm install eslint \
      eslint-config-airbnb \
      eslint-config-prettier \
      eslint-plugin-flowtype \
    eslint-plugin-import \
    eslint-plugin-prettier
    # Run eslint
    - node_modules/eslint/bin/eslint.js .